name: Update dependencies
on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * 0"

permissions:
  contents: read

jobs:
  update_deps:
    permissions:
      contents: write  # for peter-evans/create-pull-request to create branch
      pull-requests: write  # for peter-evans/create-pull-request to create a PR
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{secrets.GH_TOKEN_KOENKK}}
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npx npm-check-updates -u
    - run: npm install
    - uses: peter-evans/create-pull-request@v5
      with:
        commit-message: "feat(ignore): update dependencies"
        branch: "update_deps"
        title: Update dependencies
